theme: jekyll-theme-architect

title: [jsonb-spec]
description: [Java API for JSON Binding (JSR 367)]

# sidebar links url
links:
  source: https://github.com/javaee/jsonb-spec
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

